##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
  
robot_cfg:
  kinematics:
    use_root_pose: True
    hand_pose_transfer_path: "hand_pose_transfer/franka_ext.yml"
    tendon_joints: [['panda_finger_joint1','panda_finger_joint2']]
    use_usd_kinematics: False
    usd_robot_root: "/panda"
    usd_flip_joints: ["panda_finger_joint1", "panda_finger_joint2"]
    usd_flip_joints: {
    "panda_finger_joint1": "Y",
     "panda_finger_joint2":  "Y",
    }
    
    usd_flip_joint_limits: ["panda_finger_joint2"]
    urdf_path: "robot/franka_extensions_240704/franka_with_gripper_extensions.urdf"
    asset_root_path: "robot/franka_extensions_240704"
    base_link: "panda_hand"
    ee_link: "panda_leftfinger"
    link_names: ["panda_leftfinger", "panda_rightfinger"]
    collision_link_names:
      [
        "panda_hand",
        "panda_leftfinger",
        "panda_rightfinger",
      ]
    collision_spheres: "spheres/franka_ext.yml"
    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    use_global_cumul: True
    self_collision_ignore:
      {
        "panda_hand": ["panda_leftfinger", "panda_rightfinger"],
        "panda_leftfinger": ["panda_rightfinger"],
        "panda_rightfinger": [],
      }
    
    self_collision_buffer:
      {
        "panda_hand": 0.003,
        "panda_leftfinger": 0.003,
        "panda_rightfinger": 0.003,
      }
    mesh_link_names:
      [
        "basebody1_link",
        "basebody2_link",
        "panda_leftfinger",
        "panda_rightfinger",
      ]
    lock_joints: null
    extra_links: {}
    cspace:
      joint_names: ["panda_finger_joint1", "panda_finger_joint2"]
      retract_config: [0.04, 0.04]
      null_space_weight: [1,1]
      cspace_distance_weight: [1,1]
      max_acceleration: 15.0
      max_jerk: 500.0
