##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
  
robot_cfg:
  kinematics:
    tendon_joints: [['panda_finger_joint1','panda_finger_joint2']]
    use_usd_kinematics: False
    usd_robot_root: "/panda"
    usd_flip_joints: ["panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
      "panda_joint6","panda_joint7","panda_finger_joint1", "panda_finger_joint2"]
    usd_flip_joints: {
      "panda_joint1": "Z",
      "panda_joint2": "Z",
      "panda_joint3": "Z",
      "panda_joint4": "Z",
      "panda_joint5": "Z",
      "panda_joint6": "Z",
      "panda_joint7": "Z",
      "panda_finger_joint1": "Y",
      "panda_finger_joint2":  "Y",
    }
    
    usd_flip_joint_limits: ["panda_finger_joint2"]
    urdf_path: "robot/franka_extensions_240704/franka_with_gripper_extensions.urdf"
    asset_root_path: "robot/franka_extensions_240704"
    base_link: "panda_link0"
    ee_link: "panda_hand"
    collision_link_names:
      [
        "panda_link0",
        "panda_link1",
        "panda_link2",
        "panda_link3",
        "panda_link4",
        "panda_link5",
        "panda_link6",
        "panda_link7",
        "panda_hand",
        "panda_leftfinger",
        "panda_rightfinger",
      ]
    collision_spheres: "spheres/franka_ext.yml"
    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    use_global_cumul: True
    self_collision_ignore:
      {
        "panda_link0": ["panda_link1", "panda_link2"],
        "panda_link1": ["panda_link2", "panda_link3", "panda_link4"],
        "panda_link2": ["panda_link3", "panda_link4"],
        "panda_link3": ["panda_link4", "panda_link6"],
        "panda_link4":
          ["panda_link5", "panda_link6", "panda_link7", "panda_link8"],
        "panda_link5": ["panda_link6", "panda_link7", "panda_hand","panda_leftfinger", "panda_rightfinger"],
        "panda_link6": ["panda_link7", "panda_hand", "panda_leftfinger", "panda_rightfinger"],
        "panda_link7": ["panda_hand", "panda_leftfinger", "panda_rightfinger"],
        "panda_hand": ["panda_leftfinger", "panda_rightfinger"],
        "panda_leftfinger": ["panda_rightfinger"],
        "panda_rightfinger": [],
        
      }
    
    self_collision_buffer:
      {
        "panda_link0": 0.1, 
        "panda_link1": 0.05, 
        "panda_link2": 0.0,
        "panda_link3": 0.0,
        "panda_link4": 0.0,
        "panda_link5": 0.0,
        "panda_link6": 0.0,
        "panda_link7": 0.0,
        "panda_hand": 0.003,
        "panda_leftfinger": 0.003,
        "panda_rightfinger": 0.003,
      }
    mesh_link_names:
      [
        "panda_link0",
        "panda_link1",
        "panda_link2",
        "panda_link3",
        "panda_link4",
        "panda_link5",
        "panda_link6",
        "panda_link7",
        "basebody1_link",
        "basebody2_link",
        "panda_leftfinger",
        "panda_rightfinger",
      ]
    lock_joints: null
    extra_links: {}
    cspace:
      joint_names: ["panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
        "panda_joint6","panda_joint7","panda_finger_joint1", "panda_finger_joint2"]
      retract_config: [0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04]
      null_space_weight: [1,1,1,1,1,1,1,1,1]
      cspace_distance_weight: [1,1,1,1,1,1,1,1,1]
      max_acceleration: 15.0
      max_jerk: 500.0
