world:
  indicator: '{$OBJECT_CODE}'
  template_path: "object/new_meshdata/{$OBJECT_CODE}/mesh/simplified.obj"
  additional_cfg_path: "collision_table.yml"
  selection:
    id_lst_path: /mnt/disk1/jiayichen/data/dex_obj/meshdata_splits/new_table_density_1000_obb_0_2.json
    id:    
    start: 0
    end: 250
    repeat: 8
    shuffle: True 
  base_info_path: object/new_meshdata/{$OBJECT_CODE}/info/simplified.json
  urdf_path: object/new_meshdata/{$OBJECT_CODE}/urdf/coacd.urdf
  fixed_scale_lst: [0.06, 0.08, 0.10, 0.12]
  pose_path: object/new_meshdata/{$OBJECT_CODE}/info/tabletop_pose.json
  # scale_path: object/new_meshdata/{$OBJECT_CODE}/info/tabletop_scale.json


robot_file: "leap.yml"
robot_file_with_arm: 
base_cfg_file: "base_grasp.yml"
particle_file: "particle_grasp_debug.yml"
gradient_file: "gradient_grasp_fc.yml"

exp_name: 'v1126'
seed_num: 10
seeder_cfg:
  obj_sample:
    num: 128
    inflate: 0.1
    convex_hull: True
    collision_free: True 
  ik_init_q:
  load_path: 
  skip_transfer: False
  t:  
  r:  
  q: [ 0.5, 0, 0.5, 0., 0.5, 0, 0.5, 0, 0.5, 0, 0.5, 0, 1.58, 0, -0.5, -0.5]  
  jitter_angle: [[-180, -15, -15], [180, 15, 15]]
  jitter_dist: [[0.0, -0.03, -0.03], [0.03, 0.03, 0.03]]

grasp_contact_strategy:
  contact_points_name: ['fingertip/1', 'fingertip_2/1', 'fingertip_3/1', 'thumb_fingertip/3']
  opt_progress: [0.0, 0.6, 0.8]
  distance: [0.01, 0.01, 0.0]
  save_qpos: [False, True]
  max_ge_stage: 0

grasp_cfg:
  task_dict:
    f: [0, 0, 1]
    p: [0, 0, 0]
    t: [0, 0, 0]
    gamma: 30
  ge_param:
    type: 'qp'
    miu_coef: [0.1, 0]
    solver_type: 'batch_reluqp'
    k_lower: 0.2
    pressure_constraints:   # [contact_id_list, lower]
      [[[0, 1, 2, 3], 1.0],
        [[0, 1], 0.4], 
        [[3], 0.5], 
      ]
    enable_density: False
    solve_interval: 5

mogen_init: [3.5643, -1.5991, -1.8872, -3.0432, -0.9848,  3.2433,  0.1738, -0.2078, 0,0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,0]
eval_contact_group: []