world:
  indicator: '{$OBJECT_CODE}'
  candidate:
    template_npy_path: 
    template_cfg_path: 
    template_obj_path: "object/meshdata/{$OBJECT_CODE}/coacd/simply.obj"
    additional_cfg_path: "collision_table.yml"
  selection:
    id_lst_path: 
    id:     ['mujoco_CHICKEN_RACER']
    start: 0
    end: 1
    repeat: 4
    shuffle: True 
  mesh_info:
    base_info_path: object/meshdata/{$OBJECT_CODE}/info.json
    fixed_scale_lst: [0.06, 0.08, 0.10, 0.12]
    sim_pose_path: object/meshdata/{$OBJECT_CODE}/tabletop_pose.json



robot_file: "franka_ext_ee.yml"
robot_file_with_arm: "franka_ext.yml"
base_cfg_file: "base_grasp.yml"
particle_file: "particle_grasp_debug.yml"
gradient_file: "gradient_grasp_parallel.yml"

exp_name: 'debug'
seed_num: 1000
seeder_cfg:
  obj_inflate: 0.1
  obj_sample_num: 128
  ik_init_q:
  load_path: 
  skip_transfer: False
  t:  
  r:  
  q: [ 0.04, 0.04] 
  jitter_angle: [[-180, -15, -15], [180, 15, 15]]
  jitter_dist: [[0.0, -0.03, -0.03], [0.03, 0.03, 0.03]]


grasp_contact_strategy:
  contact_points_name: ['panda_leftfinger/4', 'panda_rightfinger/4']
  opt_progress: [0.0, 0.8]
  distance: [0.0, 0.0]
  contact_query_mode: [-1, -1]
  save_qpos: [False]
  max_ge_stage: 0

grasp_cfg:
  task_dict:
    f: [0, 0, 1]
    p: [0, 0, 0]
    t: [0, 0, 0]
    gamma: 180
  ge_param:
    type: 'dfc'
    miu_coef: [0.1, 0]
    enable_density: False
    solver_type: 'batch_reluqp'
    k_lower: 0.2
    pressure_constraints:   # [contact_id_list, lower]
      [[[0, 1], 1.0]]
    solve_interval: 5

mogen_init: [0,0,0,0, 0,0,0,0,0]
eval_contact_group: [
  ["panda_leftfinger"],
  ["panda_rightfinger"],
]