world:
  indicator: '{$OBJECT_CODE}'
  template_path: "object/objaverse/{$OBJECT_CODE}/mesh/simplified.obj"
  additional_cfg_path: 
  selection:
    id_lst_path: /mnt/disk1/jiayichen/code/cuDex/rest.json
    id:    
    start: 0
    end: 502
    repeat: 6
    shuffle: False 
  base_info_path: object/objaverse/{$OBJECT_CODE}/info/simplified.json
  urdf_path: object/objaverse/{$OBJECT_CODE}/urdf/coacd.urdf
  fixed_scale_lst: [0.05, 0.08, 0.11, 0.14, 0.17, 0.20]
  pose_path: object/objaverse/{$OBJECT_CODE}/info/tabletop_pose.json


robot_file: "allegro.yml"
robot_file_with_arm: 
base_cfg_file: "base_grasp.yml"
particle_file: "particle_grasp_debug.yml"
gradient_file: "gradient_grasp_fc.yml"

exp_name: 'objaverse'
seed_num: 100
seeder_cfg:
  obj_sample:
    num: 128
    inflate: 0.1
    convex_hull: True
    collision_free: True 
  ik_init_q:
  load_path: 
  skip_transfer: False
  t:  
  r:  
  q: [0., 0.6, 0., 0., 0., 0.6, 0., 0., 0., 0.6, 0., 0., 1.2, 0., 0., 0.,]
  jitter_angle: [[-180, -15, -15], [180, 15, 15]]
  jitter_dist: [[0.0, -0.03, -0.03], [0.03, 0.03, 0.03]]

grasp_contact_strategy:
  contact_points_name: ['link_3.0_tip/0', 'link_7.0_tip/0', 'link_11.0_tip/0', 'link_15.0_tip/0']
  opt_progress: [0.0, 0.6, 0.8]
  distance: [0.01, 0.01, 0.0]
  contact_query_mode: [-1, 0, 0]
  save_qpos: [False, True]
  max_ge_stage: 0

grasp_cfg:
  task_dict:
    f: [0, 0, 1]
    p: [0, 0, 0]
    t: [0, 0, 0]
    gamma: 180
  ge_param:
    type: 'qp'
    miu_coef: [0.1, 0]
    solver_type: 'batch_reluqp'
    k_lower: 0.2
    pressure_constraints:   # [contact_id_list, lower]
      [[[0, 1, 2, 3], 1.0],
        [[0, 1], 0.4], 
        [[3], 0.5], 
      ]
    enable_density: False
    solve_interval: 5

mogen_init: [3.5643, -1.5991, -1.8872, -3.0432, -0.9848,  3.2433,  0.1738, -0.2078, 0,0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,0]
eval_contact_group: [
  ['link_0.0', 'link_1.0', 'link_2.0', 'link_3.0', 'link_3.0_tip'],
  ['link_4.0', 'link_5.0', 'link_6.0', 'link_7.0', 'link_7.0_tip'],
  ['link_8.0', 'link_9.0', 'link_10.0', 'link_11.0', 'link_11.0_tip'],
  ['link_12.0', 'link_13.0', 'link_14.0', 'link_15.0', 'link_15.0_tip']  
]